print ("Data 1")
Nama1 = input ("nama:")
NPM1 = input ("NPM:")
Alamat1 = input ("alamat:")
print ("Data 2")
Nama2 = input ("nama:")
NPM2 = input ("NPM:")
Alamat2 = input ("alamat:")
print ("Data 3")
Nama3 = input ("nama:")
NPM3 = input ("NPM:")
Alamat3 = input ("alamat:")
print ("============")
print ("Biodata Anda")
print ("============")
print ("---------------------------------------------------------------------------------------------------")
print ("|                 NAMA	                |	  NPM	       |	    ALAMAT	|")
print ("Data1 \t= \t " +str(Nama1)+" \t\t "+str(NPM1)+"\t\t"+str(Alamat1))
print ("Data2 \t= \t " +str(Nama2)+" \t\t "+str(NPM2)+"\t\t"+str(Alamat2))
print ("Data3 \t= \t " +str(Nama3)+" \t\t "+str(NPM3)+"\t\t"+str(Alamat3))
print ("---------------------------------------------------------------------------------------------------")

jawab = 'ya'
hitung = 0

while(jawab == 'ya'):
    hitung += 1
    jawab = input("Ulang lagi tidak? ")

print ("Total perulagan: " + str(hitung))

print ("Data 1")
Nama1 = input ("nama:")
NPM1 = input ("NPM:")
Alamat1 = input ("alamat:")
print ("Data 2")
Nama2 = input ("nama:")
NPM2 = input ("NPM:")
Alamat2 = input ("alamat:")
print ("Data 3")
Nama3 = input ("nama:")
NPM3 = input ("NPM:")
Alamat3 = input ("alamat:")
print ("============")
print ("Biodata Anda")
print ("============")
print ("---------------------------------------------------------------------------------------------------")
print ("|                 NAMA	                |	  NPM	       |	    ALAMAT	|")
print ("Data1 \t= \t " +str(Nama1)+" \t\t "+str(NPM1)+"\t\t"+str(Alamat1))
print ("Data2 \t= \t " +str(Nama2)+" \t\t "+str(NPM2)+"\t\t"+str(Alamat2))
print ("Data3 \t= \t " +str(Nama3)+" \t\t "+str(NPM3)+"\t\t"+str(Alamat3))
print ("---------------------------------------------------------------------------------------------------")
